### ISSUE TITLE
Missing dependecy to setuptools

### ISSUE THREAD

**Issue by KalleDK** [Azure/pytest-azurepipelines#88]
setuptools should be added to install_requires in setup.py

```
  File "/home/vsts/work/1/s/.venv/lib/python3.11/site-packages/pytest_azurepipelines.py", line 7, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by tonybaloney** [comment]
thanks for the report. That package within setuptools is also deprecated, so I'm going to change the import for another

**Comment by KalleDK** [comment]
It might just be me, but I can't see any changes that would fix it in the PR?

**Comment by KalleDK** [comment]
Thanks @tonybaloney
